### ISSUE TITLE
Vieb URL is blocking state bar?

### ISSUE THREAD

**Issue by djasnowski** [i3d/term-themes#1]
![image](https://user-images.githubusercontent.com/616320/128667266-ae5ecf48-2e93-4279-bb75-048e23ed5c18.png)

On Fedora 34

It seems like it's blocking the mode/state bar

**Comment by i3d** [comment]
Yeah... I _think_ this is a feature, not a bug. So my vieb theme utilizes a mode called mini mode. In this mode, the control objects will be squeezed as much as possible to leave room for the web page content. If you look at the matrix.css file under the vieb config dir, you could see such settings. If you don't like such minimum setting style, you could perhaps just change the related part (the part annotated with mini mode) to something you like (or to the default).

**Comment by djasnowski** [comment]
So... you don't mind that your insert/normal/etc state is blocked? How can I change it to default view? Thank you.

**Comment by i3d** [comment]
What do you mean by "blocked"? In mini mode, the vim mode state is only *ONE* letter at the edge of the entire page (at the left bottom of the corner). That's all I need.

So if you look at the matrix.css file, you can see that there is a comment indicating the insert of the mini mode

/* mini mode */
...
/* mini mode */

I think what you can try is to remove that chunk (or comment it out entirely), then add this

  #mode {    
    text-transform: none;    
    font-size: 110%;    
  }    
  #mode-suggestions {    
    text-transform: none;    
    background: var(--fg);    
  }    
  #logo {    
    display: none;    
  }

**Comment by djasnowski** [comment]
Ah, I see. Thank you.
